### PR TITLE
1. add support for useful views like layout literals(DockLayout), HeaderFooterLayout, DatePicker, TabBar; 2. bugfixes.

### PR DESCRIPTION
**Pull request by BodhiHu**

### CODE REVIEW

**Comment by BodhiHu** [comment]
Hi @gadicc , this PR required a forked version of famous-flex of mine, which included some useful widgets of IjzerenHein, like RefreshLoader & AutosizeTextArea.

**Comment by BodhiHu** [comment]
on the other hand you might take a look at commit https://github.com/ShawnOceanHu/fview-flex/commit/bbe0f1e8608800dc00b088a96ede578a11eae6e6, which is weird : )

**Comment by gadicc** [comment]
Yes, Shawn, you legend!  I'm super swamped at the moment and have a big backlog on famous-views never mind fview-flex.  Very grateful to have some user contributions here, I know this is one of the very high demand plugins.

I had a very brief look at the diffs and all looks good.  Seems like you have a very good understanding of famous-views which is great!

Re the pipe method, as long as stuff can be "flicked" easily, that's been my only goal... there issues when e.g. both the flex's container and flex's children were piped back to it that interfered with where and how smoothly the user could scroll.

Although I think just the commit messages summarize the work, it would be great if you could update the History.md file as well, and README if/where necessary :)  Also clarifying the differences in your fork of fview-flex.  Let me know also if you feel all the work is release ready, and/or if there are any more changes you have planned before then.

Many thanks for your contribution here!

**Comment by BodhiHu** [comment]
Hi Gadicc, really glad to contribute : )
I have updated the README.md & History.md, also bumped the version to 0.0.5.
Right now basically all the flex components including some useful helper views like RefreshLoader, AutosizeTextAreaSurface can be used through JS if not available from template.

**Comment by gadicc** [comment]
Amazing!  Thanks again.  I think just including the widgets even without template helpers is a great start and people will appreciate it, especially the code samples you gave in the README.  Published as v0.0.5 :)

**Pull request merged**
